#!/bin/sh
# Build the macOS menu bar helper as one universal binary, stamped with the
# package version and signed ad hoc. Output: native/bin/sidescreen-menubar.
set -eu
cd "$(dirname "$0")/.."

if [ "$(uname -s)" != "Darwin" ]; then
  echo "build-menubar: the menu bar helper builds on macOS only; this is $(uname -s)" >&2
  exit 1
fi
for tool in swiftc lipo codesign node; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "build-menubar: $tool is missing; install the Xcode Command Line Tools (xcode-select --install)" >&2
    exit 1
  fi
done

version=$(node -p "require('./package.json').version")
src=native/menubar
out=native/bin
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

printf '// Generated by scripts/build-menubar.sh from package.json. Not committed.\nlet menubarVersion = "%s"\n' "$version" > "$src/Version.swift"
mkdir -p "$out"
for arch in arm64 x86_64; do
  swiftc -O -target "$arch-apple-macosx11.0" -o "$tmp/$arch" "$src"/*.swift
done
lipo -create -output "$out/sidescreen-menubar" "$tmp/arm64" "$tmp/x86_64"
codesign --force -s - --identifier dev.sidescreen.menubar "$out/sidescreen-menubar"
echo "built $out/sidescreen-menubar $version ($(lipo -archs "$out/sidescreen-menubar"))"
